/*
-- Query: SELECT * FROM acwm.rooms_cubicles
LIMIT 0, 1000

-- Date: 2019-03-27 14:37
*/

drop table if exists rooms_cubicles;

create table rooms_cubicles(
	id					int(11) primary key,
    location			varchar(255),
    room_cubicle_number	int(11)
);

INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (1,'Arcadia',1);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (2,'Arcadia',2);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (3,'Arcadia',3);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (4,'Arcadia',4);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (5,'Arcadia',5);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (6,'Arcadia',6);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (7,'Arcadia',7);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (8,'Arcadia',8);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (9,'Arcadia',9);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (10,'Arcadia',10);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (11,'Arcadia',11);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (12,'Arcadia',12);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (13,'Arcadia',13);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (14,'Arcadia',14);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (15,'Arcadia',15);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (16,'Arcadia',16);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (17,'Arcadia',17);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (18,'Arcadia',18);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (19,'Arcadia',19);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (20,'Arcadia',20);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (21,'Arcadia',21);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (22,'Arcadia',22);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (23,'Arcadia',23);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (24,'Arcadia',24);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (25,'Arcadia',25);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (26,'Arcadia',26);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (27,'Arcadia',27);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (28,'Arcadia',28);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (29,'Arcadia',29);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (30,'Arcadia',30);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (31,'Arcadia',31);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (32,'Arcadia',32);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (33,'Arcadia',33);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (34,'Arcadia',34);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (35,'Arcadia',35);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (36,'Arcadia',36);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (37,'Arcadia',37);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (38,'Arcadia',38);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (39,'Arcadia',39);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (40,'Arcadia',40);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (41,'Arcadia',41);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (42,'Arcadia',42);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (43,'Arcadia',43);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (44,'Arcadia',44);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (45,'Arcadia',45);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (46,'Arcadia',46);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (47,'Arcadia',47);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (48,'Arcadia',48);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (49,'Arcadia',49);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (50,'Arcadia',50);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (51,'Arcadia',51);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (52,'Arcadia',52);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (53,'Arcadia',53);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (54,'Arcadia',54);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (55,'Arcadia',55);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (56,'Arcadia',56);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (57,'Arcadia',57);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (58,'Arcadia',58);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (59,'Arcadia',59);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (60,'Arcadia',60);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (61,'Arcadia',61);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (62,'Arcadia',62);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (63,'Arcadia',63);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (64,'Arcadia',64);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (65,'Arcadia',65);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (66,'Arcadia',66);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (67,'Arcadia',67);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (68,'Arcadia',68);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (69,'Arcadia',69);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (70,'Arcadia',70);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (71,'Arcadia',71);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (72,'Arcadia',72);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (73,'Arcadia',73);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (74,'Arcadia',74);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (75,'Arcadia',75);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (76,'Arcadia',76);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (77,'Arcadia',77);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (78,'Arcadia',78);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (79,'Arcadia',79);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (80,'Arcadia',80);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (81,'Arcadia',81);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (82,'Arcadia',82);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (83,'Arcadia',83);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (84,'Arcadia',84);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (85,'Arcadia',85);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (86,'Arcadia',86);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (87,'Arcadia',87);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (88,'Arcadia',88);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (89,'Arcadia',89);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (90,'Arcadia',90);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (91,'Arcadia',91);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (92,'Arcadia',92);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (93,'Arcadia',93);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (94,'Arcadia',94);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (95,'Arcadia',95);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (96,'Arcadia',96);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (97,'Arcadia',97);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (98,'Arcadia',98);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (99,'Arcadia',99);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (100,'Arcadia',100);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (101,'Arcadia',101);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (102,'Arcadia',102);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (103,'Arcadia',103);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (104,'Arcadia',104);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (105,'Arcadia',105);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (106,'Arcadia',106);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (107,'Arcadia',107);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (108,'Arcadia',108);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (109,'Arcadia',109);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (110,'Arcadia',110);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (111,'Arcadia',111);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (112,'Arcadia',112);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (113,'Arcadia',113);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (114,'Arcadia',114);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (115,'Arcadia',115);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (116,'Arcadia',116);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (117,'Arcadia',117);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (118,'Arcadia',118);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (119,'Arcadia',119);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (120,'Arcadia',120);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (121,'Arcadia',121);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (122,'Arcadia',122);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (123,'Arcadia',123);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (124,'Arcadia',124);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (125,'Arcadia',125);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (126,'Arcadia',126);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (127,'Arcadia',127);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (128,'Arcadia',128);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (129,'Arcadia',129);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (130,'Arcadia',130);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (131,'Arcadia',131);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (132,'Arcadia',132);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (133,'Arcadia',133);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (134,'Arcadia',134);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (135,'Arcadia',135);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (136,'Arcadia',136);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (137,'Arcadia',137);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (138,'Arcadia',138);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (139,'Arcadia',139);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (140,'Arcadia',140);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (141,'Arcadia',141);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (142,'Arcadia',142);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (143,'Arcadia',143);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (144,'Arcadia',144);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (145,'Arcadia',145);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (146,'Arcadia',146);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (147,'Arcadia',147);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (148,'Arcadia',148);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (149,'Arcadia',149);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (150,'Arcadia',150);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (151,'Arcadia',151);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (152,'Arcadia',152);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (153,'Arcadia',153);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (154,'Arcadia',154);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (155,'Arcadia',155);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (156,'Arcadia',156);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (157,'Arcadia',157);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (158,'Arcadia',158);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (159,'Arcadia',159);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (160,'Arcadia',160);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (161,'Arcadia',161);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (162,'Arcadia',162);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (163,'Arcadia',163);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (164,'Arcadia',164);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (165,'Arcadia',165);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (166,'Arcadia',166);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (167,'Arcadia',167);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (168,'Arcadia',168);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (169,'Arcadia',169);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (170,'Arcadia',170);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (171,'Arcadia',171);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (172,'Arcadia',172);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (173,'Arcadia',173);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (174,'Arcadia',174);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (175,'Arcadia',175);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (176,'Arcadia',176);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (177,'Arcadia',177);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (178,'Arcadia',178);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (179,'Arcadia',179);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (180,'Arcadia',180);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (181,'Arcadia',181);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (182,'Arcadia',182);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (183,'Arcadia',183);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (184,'Arcadia',184);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (185,'Arcadia',185);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (186,'Arcadia',186);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (187,'Arcadia',187);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (188,'Arcadia',188);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (189,'Arcadia',189);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (190,'Arcadia',190);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (191,'Arcadia',191);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (192,'Arcadia',192);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (193,'Arcadia',193);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (194,'Arcadia',194);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (195,'Arcadia',195);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (196,'Arcadia',196);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (197,'Arcadia',197);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (198,'Arcadia',198);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (199,'Arcadia',199);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (200,'Arcadia',200);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (201,'South Gate',1);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (202,'South Gate',2);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (203,'South Gate',3);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (204,'South Gate',4);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (205,'South Gate',5);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (206,'South Gate',6);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (207,'South Gate',7);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (208,'South Gate',8);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (209,'South Gate',9);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (210,'South Gate',10);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (211,'South Gate',11);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (212,'South Gate',12);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (213,'South Gate',13);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (214,'South Gate',14);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (215,'South Gate',15);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (216,'South Gate',16);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (217,'South Gate',17);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (218,'South Gate',18);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (219,'South Gate',19);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (220,'South Gate',20);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (221,'South Gate',21);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (222,'South Gate',22);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (223,'South Gate',23);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (224,'South Gate',24);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (225,'South Gate',25);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (226,'South Gate',26);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (227,'South Gate',27);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (228,'South Gate',28);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (229,'South Gate',29);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (230,'South Gate',30);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (231,'South Gate',31);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (232,'South Gate',32);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (233,'South Gate',33);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (234,'South Gate',34);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (235,'South Gate',35);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (236,'South Gate',36);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (237,'South Gate',37);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (238,'South Gate',38);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (239,'South Gate',39);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (240,'South Gate',40);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (241,'South Gate',41);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (242,'South Gate',42);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (243,'South Gate',43);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (244,'South Gate',44);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (245,'South Gate',45);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (246,'South Gate',46);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (247,'South Gate',47);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (248,'South Gate',48);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (249,'South Gate',49);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (250,'South Gate',50);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (251,'South Gate',51);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (252,'South Gate',52);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (253,'South Gate',53);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (254,'South Gate',54);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (255,'South Gate',55);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (256,'South Gate',56);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (257,'South Gate',57);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (258,'South Gate',58);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (259,'South Gate',59);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (260,'South Gate',60);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (261,'South Gate',61);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (262,'South Gate',62);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (263,'South Gate',63);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (264,'South Gate',64);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (265,'South Gate',65);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (266,'South Gate',66);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (267,'South Gate',67);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (268,'South Gate',68);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (269,'South Gate',69);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (270,'South Gate',70);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (271,'South Gate',71);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (272,'South Gate',72);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (273,'South Gate',73);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (274,'South Gate',74);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (275,'South Gate',75);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (276,'South Gate',76);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (277,'South Gate',77);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (278,'South Gate',78);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (279,'South Gate',79);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (280,'South Gate',80);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (281,'South Gate',81);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (282,'South Gate',82);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (283,'South Gate',83);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (284,'South Gate',84);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (285,'South Gate',85);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (286,'South Gate',86);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (287,'South Gate',87);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (288,'South Gate',88);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (289,'South Gate',89);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (290,'South Gate',90);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (291,'South Gate',91);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (292,'South Gate',92);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (293,'South Gate',93);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (294,'South Gate',94);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (295,'South Gate',95);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (296,'South Gate',96);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (297,'South Gate',97);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (298,'South Gate',98);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (299,'South Gate',99);
INSERT INTO `rooms_cubicles` (`id`,`location`,`room_cubicle_number`) VALUES (300,'South Gate',100);
